### PR TITLE
cleanup sample

### PR DESCRIPTION
**Pull request by stevenweber**
Makes sample more realistic and only includes non-defaulted inputs, i.e. the bare minimum config.

### CODE REVIEW

**Comment by ebenoist** [comment]
^^ Is the problem I had before with the "defaults"

**Comment by ebenoist** [comment]
defaults, eh? we should probably dig in someday and figure out why?

**Comment by stevenweber** [comment]
Docs state that defaults should be added in the env like explicit inputs, but not seeing them. Could be an issue with using a path, bug in general, etc. Regardless, any concerns including values for optional/defaulted values fields in the sample workflow?

**Comment by ebenoist** [comment]
Nope. I left them in there originally for exactly this reason :)

**Pull request merged**
